### ISSUE TITLE
Extension not active

### ISSUE THREAD

**Issue by franklichnok** [bheisig/rt-extension-referenceidoitobjects#2]
Installed the extension successfully, activated it, short test fails because of false version of i-doit. So I commented out the lines in RT_SiteConfig.pm to deactivate the extension till upgrade of i-doit. After that, I removed the comments to re-activate the extension, but it doesn't work. I see the custom fields of the extension, but no dialogue for the connection to i-doit. In /opt/rt4/var/mason_data/obj no folder for the extension. How can I fix this? Thank you in advance!

**Comment by bheisig** [comment]
Which versions of RT and i-doit have you installed? There is a [common issue in RT 4.4.x](https://github.com/bheisig/rt-extension-referenceidoitobjects#issue-in-rt-44x) because of an out-dated JavaScript plugin.

**Comment by franklichnok** [comment]
Sorry for being late. The problem is solved…it was in front of the computer.I just misconfigured it. Now it’s fixed an works fine.

Kind regards

**Comment by bheisig** [comment]
Sounds good. Have fun with i-doit and RT :-)
