### ISSUE TITLE
i-doIT Integration - no tickets shown

### ISSUE THREAD

**Issue by franklichnok** [bheisig/rt-extension-referenceidoitobjects#3]
Got the plugin for RT up and running. When creating a ticket in RT, I can select assets from i-doIT. The assigned object is shown in the ticket. But when I try to show all tickets for the object in i-doIT, there are no tickets. But the log of i-doIT shows an entry for the ticket creation with the correct values from RT.

I've checked the i-doIT-manual, but the part for RT is not very useful for this. Any ideas what I can check to solve this? Thank you in advance!

Frank

**Comment by bheisig** [comment]
Hi Frank,

Thanks for your comment. This looks like your issue isn't directly related to this RT extension. Have you double-checked the i-doit KB article "[Service desk](https://kb.i-doit.com/display/en/Service+Desk)" to configure i-doit properly? If it's still an issue please file a bug report within the [i-doit help center](https://help.i-doit.com/). Thanks.

Greetings,
Ben
